logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
    org.springframework.security.web.csrf: DEBUG

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: ''

    url: jdbc:mysql://localhost:3306/liquibase_db?createDatabaseIfNotExist=true
  liquibase:
    change-log: classpath:db/changelog/liquibase-changelog.xml
    default-schema:

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

  mvc:
    hidden-method:
      filter:
        enabled: true
  security:
    user:
      name: admin
      password: admin

server:
  port: 8000